In [ ]:
import torch

In [ ]:
my_tensor = torch.tensor([[1,2,3], [4,5,6]])
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32, device='cuda')
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [ ]:
my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32, device='cpu')
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32, device='cpu', requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [ ]:
Device = 'cuda' if torch.cuda.is_available() else 'cpu'

my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32, device=Device, requires_grad=True)

print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [ ]:
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])
True


### Initialisation Methods

In [ ]:
x = torch.empty(size=(3,3))
y = torch.zeros((3,3))
z = torch.rand((3,3))
q = torch.eye(3,3)
w = torch.arange(start=0, end= 5, step=1)
e = torch.linspace(start = 0.1, end=1, steps=10)
r = torch.empty(size=(1,5)).normal_(mean=0, std=1)
t = torch.empty(size= (1,5)).uniform_(0,1)
z = torch.diag(torch.ones(3))


## How to initialize and convert tensors to other typer (int, float, double)

In [ ]:
tensor = torch.arange(4)

print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


### Array to tensor conversion and vice versa

In [ ]:
import numpy as np

np_array = np.array((5,5))
tensor = torch.from_numpy(np_array)
np_array_back = tensor.numpy()


## Tensor math and comparison operations

In [ ]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

# Addition
z1 = torch.add(x,y)
z2 = x+y
print(z1)
print(z2)

# Subtraction

z3 = y - x

# Division

z4 = torch.true_divide(x, y)

# Inplace operations
t = torch.zeros(3)
t.add_(x)
print('t:', t)

tensor([10, 10, 10])
tensor([10, 10, 10])
t: tensor([1., 2., 3.])


In [ ]:
# Exponentiation

u1 = x.pow(2)
u2 = x ** 2

In [ ]:
# Value comparison

z1 = x < 0
z2 = x > 0

print(z1, z2)

tensor([False, False, False]) tensor([True, True, True])


In [ ]:
# Matrix Multiplication

x1 = torch.rand([2,5])
x2 = torch.rand([5,3])
x3 = torch.mm(x1, x2) # 2 x 3
print(x3)

tensor([[1.0506, 1.3189, 1.0071],
        [0.7667, 0.8594, 0.8804]])


In [ ]:
# Matrix exponentiation

matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(3))

tensor([[3.0222, 1.8810, 4.2808, 3.9540, 1.9371],
        [2.9295, 1.9373, 4.0582, 3.6035, 1.8065],
        [3.3304, 2.0247, 4.6483, 4.3904, 2.0850],
        [3.9564, 2.4862, 5.6306, 5.1253, 2.6031],
        [2.6879, 1.6049, 3.7054, 3.5836, 1.6348]])


In [ ]:
# Element wise multiplication
z = x * y
z = torch.dot(x, y)

# Batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)
print(z)

tensor(46)


In [ ]:
#Example of broadcasting

x1 = torch.rand((5,5)) 
x2 = torch.rand((1, 5))

z = x1 - x2
z = x1 ** x2

In [ ]:
# Other functions
sum = torch.sum(x, dim=0)
values, indices = torch.max(x, dim=0)
values, indices = torch.min(x, dim=0)
abs_x = torch.abs(x)
z = torch.argmax(x, dim=0) # only returns the index of the max
z = torch.argmin(x, dim=0)

mean_x = torch.mean(x.float(), dim=0)
z = torch.eq(x, y) # check which elements are equal
print(z)

torch.sort(y, dim=0, descending=False)

sorted_y, indices = torch.sort(y, dim= 0, descending=False)

z = torch.clamp(x, min=0) # check all elements all value less than 0 and make them zero.


tensor([False, False, False])


In [ ]:

x = torch.tensor([1,0,1,0,1,1], dtype=torch.bool)
z = torch.any(x)
z = torch.all(x)
print(z)

tensor(False)


## Indexing in Tensors

In [ ]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

print(x[0].shape)
print(x[:, 0].shape)
print(x[2, 0:10]) # 0:10 

torch.Size([25])
torch.Size([10])
tensor([0.5908, 0.8056, 0.5954, 0.3891, 0.4277, 0.0728, 0.0277, 0.1361, 0.3231,
        0.4292])


In [ ]:
x[0,0]

tensor(0.8477)

In [ ]:
# Fancy Indexing

x = torch.arange(10)
indices = [2,5,8]
print(x[indices])

tensor([2, 5, 8])


In [ ]:
x = torch.rand((3, 5))
rows = torch.tensor([1,0])
cols = torch.tensor([4, 0])
print(x[rows, cols].shape)

torch.Size([2])


In [ ]:
# Advance indexing
x = torch.arange(10)
print(x[(x < 2) | (x > 8) ])
print(x[x.remainder(2) == 0])

tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


In [ ]:
# Other useful operations

print(torch.where(x > 5 , x, x *2))
print(torch.tensor([0,0,1,2,2,3,4]).unique())
print(x.ndimension())

print(x.numel())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


## Reshaping the tensors

In [ ]:
x = torch.arange(9)

x_3x3 = x.view(3,3)
print(x_3x3)

x_3x3 = x.reshape(3,3) # better version

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [ ]:
y = x_3x3.t()
print(y)

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [ ]:
# Concat
# torch.concat((x1, x2), dim=0)

z = x1.view(-1)  # to flat the array


batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

torch.Size([64, 10])


In [ ]:
z = x.permute(0,2,1)
print(z)

tensor([[[6.5512e-02, 8.3965e-01],
         [5.6135e-01, 7.9671e-01],
         [3.2942e-01, 2.7194e-01],
         [7.6510e-01, 8.8281e-01],
         [7.0096e-01, 7.9004e-01]],

        [[5.9699e-01, 4.2769e-01],
         [2.0012e-01, 4.4996e-01],
         [5.6564e-01, 6.5591e-01],
         [6.4971e-01, 8.9868e-01],
         [1.7925e-01, 1.6872e-01]],

        [[9.8277e-01, 2.7914e-01],
         [4.0448e-01, 3.8690e-01],
         [4.9776e-01, 4.2939e-01],
         [5.6720e-01, 7.9193e-01],
         [1.0322e-01, 1.4977e-01]],

        [[9.1280e-01, 9.4805e-01],
         [1.0683e-01, 7.0883e-01],
         [2.7691e-01, 7.6222e-01],
         [4.6695e-01, 8.8291e-01],
         [3.8386e-01, 1.8948e-01]],

        [[8.9962e-01, 5.2429e-01],
         [1.1604e-01, 7.4719e-01],
         [6.2421e-01, 6.6362e-01],
         [3.3436e-01, 9.2498e-02],
         [2.2125e-01, 9.1148e-01]],

        [[3.3584e-01, 5.0238e-01],
         [3.5969e-01, 8.9697e-01],
         [8.0765e-02, 2.0320e-01],
         [

In [ ]:
x = torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

torch.Size([1, 10])
torch.Size([10, 1])
